settings:
  title: 'Estado de la red'
  url: 'https://status.platinumservers.es' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos los sistemas operativos'
  notAllmonitorsOperational: 'Sistemas no operativos en su totalidad'
  monitorLabelOperational: 'Operativo'
  monitorLabelNotOperational: 'No operativo'
  monitorLabelNoData: 'Sin datos'
  dayInHistogramNoData: 'Sin datos'
  dayInHistogramOperational: 'Todo correcto'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: web # unique identifier
    name: 'Página web'
    url: 'http://185.47.130.200/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: ptero # unique identifier
    name: 'GameServers'
    url: 'https://ptero.platinumservers.es/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: web # unique identifier
    name: 'Hosting Web'
    url: 'http://185.47.130.200/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: fr1 # unique identifier
    name: 'Fr1'
    url: 'https://fr1.goldenservers.es:8006/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: ca1 # unique identifier
    name: 'Ca1'
    url: 'https://ca1.goldenservers.es:8006/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
